### ISSUE TITLE
[Feature] Allow to request navigation action to any parent NavController

### ISSUE THREAD

**Issue by egorikftp** [ComposeGears/Tiamat#16]
I want to call 
```kotlin
navController.parent(key).resolve(Data)
```
 \+
```kotlin
rememberNavController(..., resolver = { if(it is Data) this.navigate(...) })
```

it will be useful for multimodule navigation (without cycled dependencies)

**Comment by vkatz** [comment]
1) Will not be implements as it migh be done via compose itself
2) Made multi-module example to demonstrate one of the option (Signals/Broadcast-api)
