### ISSUE TITLE
Does this work on iOS web?

### ISSUE THREAD

**Issue by realityexpander** [ComposeGears/Tiamat#20]
Tried to use https://composegears.github.io/Tiamat/ from an iPad using 17.4.1 and Safari.

The screen shows up blank.

Works fine on my mac.

**Comment by vkatz** [comment]
@realityexpander
As far as i know - safaris have bad WASM support, as for now it works good on Chrome
We will perform some tests later on after finishing 1.1.0 release

**Comment by vkatz** [comment]
• Added message in case browser is not supported

**Comment by egorikftp** [comment]
example from Safari

<img width="1436" alt="Screenshot 2024-04-14 at 21 21 16" src="https://github.com/ComposeGears/Tiamat/assets/16294951/c322b395-c16f-457c-9696-75ca6546398c">
