### ISSUE TITLE
free args vs nav args

### ISSUE THREAD

**Issue by BioRyajenka** [ComposeGears/Tiamat#90]
Hi, whats the difference between free args and nav args?

If I need to pass multiple parameters, say, `UUID`, `Boolean`, `Boolean`, should I use data params object as nav args, or should I pass those in free args, or should I pass UUID in nav args and the other two in free args?

q2: I think I am gonna use `StorageMode.SavedState`. What are the reasons to use other storage modes? I mean, developing an app, you probably always want your nav params to be preserved... (what does it even mean?)

Thanks!

**Comment by vkatz** [comment]
@BioRyajenka 
q1:   navArgs are used to pas some fixed data related to screen details (eg: productId or productDetails for product screen)
        freeArgs are designed to pass free form of data (eg: you can pass deeplink information or some metadata used to do some actions, this data is usually not directly show's on screen and rather used as `addtion`

       if you need to pass multiple params - the best way is to create a wrapper over them eg: data class ScreenData(bool, bool, uuid)  and pass it thrue navArgs

q2  there is 2 main reasons: 
      1) some platforms are not using saveable mode (eg: desktop, u can keep all in memory and avoid extr save-load logic)
      2) talking about androind - some apps are not require `full state restore` (it means - if system kill app, it's ok to restart is from main screen)  in this case we can use InMemory storage to avoid extra save-load logic + we can use ANY!!! data types as args (including lambdas) as we will not `save` them  (ps: SavedState require all navArgs freeArgs & navResults to be saveable [as for android - bundlable])

**Comment by BioRyajenka** [comment]
Hey, thanks for quick response!

If using InMemory storage, will it survive screen rotations, quick app minimizing/maximizing? 

> if system kill app, it's ok to restart is from main screen
I would actually want my app to start from the main screen if it was killed before... (expected behavior for any app - I reckon). Does it mean I need to actually use InMemory and not SavedState, because with SavedState it will always continue from the last point?

**Comment by vkatz** [comment]
> If using InMemory storage, will it survive screen rotations, quick app minimizing/maximizing?

Yes, it's exact beheaviour we wants from this mode for Android - to survivew for a allowed by system perion (usually from 5 min till few hrs)

> SavedState it will always continue from the last point 
If u kill app (swipe) - it is a force close, so app will starts from main
if u minimize, wait for a long period of time (so system decide to halt app) and sthe tryes to maximize - it will trys to restore state

**Comment by BioRyajenka** [comment]
Gotcha, thanks!
I think InMemory should be enough for my case
